DEV_env = {
      "postgres_db": {
            'ENGINE': 'django.contrib.gis.db.backends.postgis',
            'NAME': 'library_book',
            'USER': 'postgres',
            'PASSWORD': 'postgres',
            'HOST': 'localhost',
            'PORT': 5432
      }
}

POSTGRES_DATABASE = DEV_env['postgres_db']
